name: openverse-frontend/setup-node-env
description: Setup the Node.js environment including `pnpm` and dependencies

inputs:
  install:
    default: true
    description: Whether to install dependencies.

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.1.0 # ensure that it matchers `packageManager` field in `frontend/package.json`

    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.local/share/pnpm/store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: actions/setup-node@v3.5.1
      with:
        node-version: 16
        cache: pnpm
        cache-dependency-path: |
          pnpm-lock.yaml
          .npmrc

    - name: Install
      if: inputs.install
      shell: bash
      working-directory: "frontend/"
      run: "pnpm install"

    - name: Copy locale files
      shell: bash
      working-directory: "frontend/"
      run: "cp -r test/locales/* src/locales"
