name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-env
        with:
          setup_python: false

      - name: Run unit tests
        run: just pnpm test:unit

  clean-playwright-failure-comment:
    name: Remove previous Playwright test failure comments
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - uses: peter-evans/find-comment@v2
        id: test-results-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Playwright Failure Test Results

      - uses: actions/github-script@v6
        if: steps.test-results-comment.outputs.comment-id != 0
        with:
          script: |
            await github.rest.issues.deleteComment({
              repo: context.repo.repo,
              owner: context.repo.owner,
              comment_id: ${{ steps.test-results-comment.outputs.comment-id }}
            })
            console.log('Deleted comment with ID ${{ steps.test-results-comment.outputs.comment-id }}')

  nuxt-playwright:
    name: Nuxt Playwright tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-env
        with:
          setup_python: false

      - name: Run Nuxt Playwright tests
        run: just pnpm test:playwright --workers=2

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: nuxt-test-results
          path: test-results

  storybook-playwright:
    name: Storybook Playwright tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-env
        with:
          setup_python: false

      - name: Run Storybook Playwright tests
        run: just pnpm test:storybook

      - uses: actions/upload-artifact@v3
        if: failure()
        id: test-results
        with:
          name: storybook-test-results
          path: test-results

  playwright-test-failure-comment:
    name: Share Playwright test debugging instructions
    runs-on: ubuntu-latest
    if: always() && github.ref != 'refs/heads/main' && (needs.nuxt-playwright.result == 'failure' || needs.storybook-playwright.result == 'failure')
    needs:
      - nuxt-playwright
      - storybook-playwright

    steps:
      - uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Playwright Failure Test Results**

            It looks like some of the Playwright tests failed. You can download the Playwright trace
            output for both Storybook and Nuxt Playwright tests that have failed at the bottom of this
            page, under the "Artifacts" section:

            <https://github.com/WordPress/openverse-frontend/actions/runs/${{ github.run_id }}>

            Read more about how to use this artifact here: <https://github.com/WordPress/openverse-frontend/blob/main/test/playwright/README.md#debugging>

  storybook:
    name: Check Storybook build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-env
        with:
          setup_python: false

      - name: Run Storybook smoke-test
        run: just pnpm storybook:smoke

  build:
    name: Check Nuxt build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-env
        with:
          setup_python: false

      - name: Run build
        run: just pnpm build
