name: Generate translation PO file

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-env
        with:
          setup_python: false

      - name: Generate PO
        run: just pnpm i18n:generate-pot

      - name: Copy to root
        run: cp frontend/openverse.pot /tmp/openverse.pot

      - name: Checkout `translations` branch
        uses: actions/checkout@v3
        with:
          ref: translations

      - name: Update POT on `translations` branch
        run: |
          rm -f openverse.pot
          cp /tmp/openverse.pot openverse.pot
          git config --global user.name 'POT Updater'
          git config --global user.email 'openverse@wordpress.org'
          git commit --no-verify -am 'Update POT file'
          git push --no-verify

      - name: Re-checkout `main` branch to allow for cleanup to work
        uses: actions/checkout@v3
        with:
          ref: main
