name: GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-images:
    name: Build images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - api
          - ingestion_server
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-env
        with:
          setup_python: false
          setup_nodejs: false

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build image `${{ matrix.image }}`
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.image }}
          push: false
          tags: openverse-${{ matrix.image }}
          cache-from: type=gha,scope=${{ matrix.image }}
          cache-to: type=gha,scope=${{ matrix.image }}
          outputs: type=docker,dest=/tmp/${{ matrix.image }}.tar

      - name: Upload image `${{ matrix.image }}`
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.image }}
          path: /tmp/${{ matrix.image }}.tar

  deploy:
    name: Developer docs, Storybook, Tailwind config deploy
    runs-on: ubuntu-latest
    needs:
      - build-images
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-env
        with:
          setup_python: false

      - name: Download all images
        uses: actions/download-artifact@v2
        with:
          path: /tmp

      - name: Load all images
        run: |
          docker load --input /tmp/api/api.tar
          docker load --input /tmp/ingestion_server/ingestion_server.tar

      - name: Compile Sphinx
        run: |
          just sphinx-make
          sudo chown "$USER:$USER" -R ./api
          mv ./api/build/html /tmp/gh-pages

      - name: Build Storybook
        run: |
          just pnpm i18n
          just pnpm storybook:build

      - name: Build Tailwind Config Viewer
        run: just pnpm tcv:build

      # This makes the TCV available at the `/tailwind` directory in the gh-pages
      - name: Merge TCV and Storybook builds
        run: |
          mv frontend/storybook-static /tmp/gh-pages/storybook
          mv frontend/.tcv-export /tmp/gh-pages/tailwind

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Preserve previews
        run: mv _preview /tmp/gh-pages/_preview

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/gh-pages
          force_orphan: true

      - name: Checkout branch again to enable cleaning
        if: always()
        uses: actions/checkout@v3
        with:
          ref: main
